server:
  port: 8081
spring:
  datasource:
    dynamic:
      hikari:
        connection-timeout: 30000
        max-lifetime: 1800000
        max-pool-size: 15
        min-idle: 5
        connection-test-query: select 1
      primary: base
      datasource:
        base:
          username: root
          password: ScudP@wer
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://nj-cdb-jq7pe3t9.sql.tencentcdb.com:63864/scud_isp?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # ??SQL
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl