server:
  port: 8081
spring:
  datasource:
    dynamic:
      hikari:
        connection-timeout: 30000
        max-lifetime: 1800000
        max-pool-size: 15
        min-idle: 5
        connection-test-query: select 1
      primary: base
      datasource:
        base:
          username: xxxx
          password: xxx
          driver-class-name: xxxx
          url: xxxxx

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # ??SQL
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl